site_name: PromiseWikki
site_url: https://lilly0303.github.io/PromiseWikki/  # 这里建议填你真实的GitHub Pages地址
site_author: Me

# 核心主题配置

theme:
  name: material
  language: zh
  # 网站图标
  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    # --- ☀️ 白天模式 ---
    - scheme: default
      primary: pink
      accent: pink

       

   

  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy

# 引入自定义 CSS
extra_css:
  - stylesheets/extra.css

# 引入自定义 JS
extra_javascript:
  - javascripts/extra.js

# 插件
plugins:
  - search

# 扩展语法
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji

# --- 🧭 导航菜单 ---
# ⚠️ 注意：下面的文件路径必须真实存在！
nav:
  - 'HOME': index.md
  - 'TOOLS':
      - '杂货铺': overview.md
      - '游戏逆向解包':
          - '纸房子': game_re/sweet_home.md
      - '自动化脚本' :
          - '漫蛙自动签到': scripts/ManWaAuto.md
          - '楽一番自动签到': scripts/Leyifan Automation.md
  - 'POCKET':
      - '常用链接 (总览)': resources/overview.md
      - '小说资源':
          - '搜索与导航': resources/novels/search.md
          - '在线阅读': resources/novels/sites.md
          - '下载与APP': resources/novels/download.md
      - '漫画': resources/comics.md
      - '影视与追番': resources/media.md
      - '实用工具': resources/tools.md
      - '网盘搜索': resources/disks.md
